name: number_guess_game
description: "Number Guess Challenge Game"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  google_mobile_ads: ^6.0.0
  fluttertoast: ^8.2.12

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  confetti: ^0.7.0
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/success.mp3
    - assets/high.mp3
    - assets/low.mp3
    - assets/restart.mp3
    - assets/error.mp3


flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#0F8581"
  adaptive_icon_foreground: "assets/icon/app_icon.png"