name: number_guess_game
description: "A fun number guessing game with hints, score tracking, achievements, and rewarding gameplay."

# Prevent publishing to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# App version (version_name+version_code)
version: 1.0.0+3

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # Google AdMob ads
  google_mobile_ads: ^6.0.0

  # Toast messages
  fluttertoast: ^8.2.12

  # Custom fonts
  google_fonts: ^6.3.0

  cupertino_icons: ^1.0.8

  # Local storage
  shared_preferences: ^2.2.2

  # Celebration animation
  confetti: ^0.7.0

  # Game sound effects
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # App icon generator
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  # Audio assets
  assets:
    - assets/success.mp3
    - assets/high.mp3
    - assets/low.mp3
    - assets/restart.mp3
    - assets/error.mp3

# Launcher icon configuration
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon_2.png"
  adaptive_icon_background: "#0F8581"
  adaptive_icon_foreground: "assets/icon/app_icon_2.png"